version: '3.8'
services:
  #docker compose --env-file=.env.docker up -d 

#Python Service
  python_flask:
    build:
      context: .
      dockerfile: dockerfiles/python.Dockerfile
    container_name: python_flask
    restart: "no"
    tty: true
    ports: 
      - "5000:5000"
    environment: 
      SERVICE_NAME: python_flask
    working_dir: /usr/src/app
    volumes: 
      - ${SERVER_FOLDER}:/usr/src/app
    networks: 
      - app-network
  
#Docker Networks
networks:
  app-network:
    driver: bridge
